apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cat-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cat  
    # spec:                      
    #   containers: 
    #   - name: hello-world 
    #     image: gcr.io/aydangoon/cat:v1
    #     ports:
    #     - containerPort: 3000
