---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/aydangoon/cat-app:latest
          ports:
            - containerPort: 3000
          # volumeMounts:
          #   - name: template-map
          #     mountPath: /templates
          # env:
          #   - name: REDIS_URL
          #     value: "redis://redis/0"
          #   - name: ADMIN_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: web-secret
          #         key: username
          #   - name: ADMIN_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: web-secret
          #         key: password
      # volumes:
      #   - name: template-map
      #     configMap:
      #       name: template-map
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 3000
